import type { CurrenciesData } from "./types";

export const mockCurrencyData: CurrenciesData = {
  "2025-03-03": {
    USD: {
      name: "ДОЛЛАР США",
      currency: "USD",
      date: "2025-03-03",
      logo: null,
      quant: "1",
      index: "DOWN",
      delta: -1.3,
      value: "499.22",
      sort: "1",
    },
    EUR: {
      name: "ЕВРО",
      currency: "EUR",
      date: "2025-03-03",
      logo: null,
      quant: "1",
      index: "DOWN",
      delta: -0.5,
      value: "519.14",
      sort: "2",
    },
    RUB: {
      name: "РОССИЙСКИЙ РУБЛЬ",
      currency: "RUB",
      date: "2025-03-03",
      logo: null,
      quant: "1",
      index: "DOWN",
      delta: -0.1,
      value: "5.64",
      sort: "3",
    },
    CNY: {
      name: "КИТАЙСКИЙ ЮАНЬ",
      currency: "CNY",
      date: "2025-03-03",
      logo: null,
      quant: "1",
      index: "UP",
      delta: 0.2,
      value: "68.59",
      sort: "4",
    },
    KGS: {
      name: "КЫРГЫЗСКИЙ СОМ",
      currency: "KGS",
      date: "2025-03-03",
      logo: null,
      quant: "1",
      index: "SAME",
      delta: 0,
      value: "5.71",
      sort: "5",
    },
  },
};
